In [1]:
import numpy as np

# создание вектора
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [2]:
# создание матрицы, заполненной нулями
b = np.zeros((4, 5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
# создание последовательности
c = np.arange(0, -6, -1)
c

array([ 0, -1, -2, -3, -4, -5])

In [4]:
# вывод формы массива
b.shape

(4, 5)

In [5]:
# вывод типа массива
type(b)

numpy.ndarray

In [6]:
# вывод 1й строки массива
b[0]

array([0., 0., 0., 0., 0.])

In [7]:
# вывод 2-3 строк через срез
b[1:3]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# создание вектора единиц
d = np.ones((1, 6))
print(d, type(d))

[[1. 1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [9]:
# поэлементное сложение векторов
c = c + d
c

array([[ 1.,  0., -1., -2., -3., -4.]])

In [10]:
# вывод вектора и его среднего
print(a, a.mean())

[1 2 3 4] 2.5
